#!/bin/zsh

function main(){
  quit_no_window_app
}

function quit_no_window_app(){
  osascript -e '
  tell application "System Events"
	  set apps to processes whose background only is false
	  repeat with anApp in apps
		  set appName to name of anApp
		  set windowCount to count of window of anApp
		  if windowCount is 0 and appName is not "Finder" then
			  do shell script "killall " & quoted form of appName
		  end if
	  end repeat
  end tell'
}

main

