tap 'koekeishiya/formulae'
brew 'git'
brew 'nvim'
brew 'gh'
brew 'yabai'
brew 'fswatch'
cask 'ghostty'
cask 'microsoft-word'
cask 'microsoft-excel'
cask 'microsoft-powerpoint'
cask 'arc'
brew 'jq'
brew 'sleepwatcher', postinstall:"cp sleepwatcher/wakeup ~/.wakeup", restart_sevice: :changed
