#!/bin/bash

sketchybar --bar \
  position=top \
  height=24 \
  blur_radius=2560 \
  color=0x20000000 \
  font_smoothing=on \
  shadow=on \
  padding_left=9 \
  padding_right=9 \
  show_in_fullscreen=on

sketchybar --default \
  label.font="SF Pro:Regular:13.0" \
  icon.font="SF Pro:Regular:13.0" \
  label.shadow=on \
  icon.shadow=on \
  icon.color=0xffffffff \
  label.color=0xffffffff \
  icon.padding_left=10 \
  icon.padding_right=0 \
  label.padding_left=0 \
  label.padding_right=10 \
  background.color=0x30ffffff \
  background.height=24 \
  background.corner_radius=5 \
  background.drawing=off

sketchybar \
  --add item apple left \
  --set apple icon=􀣺 \
    icon.font="SF Pro:Regular:16.0"

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"; do
  sid="$(($i+1))"
  sketchybar\
    --add space space."$sid" left\
    --set space."$sid"\
      space="$sid"\
      icon="${SPACE_ICONS[i]}"\
      icon.padding_right=5 \
      script="plugins/space.sh"\
      click_script="yabai -m space --focus $sid"    
done

sketchybar \
  --add item chevron left \
  --set chevron \
    icon.font="Liga SFMono Nerd Font:Regular:13.0" \
    icon= \
    script="plugins/space_windows.sh"\
  --subscribe chevron space_windows_change

sketchybar \
  --add item front_app left \
  --set front_app \
    label.font="SF Pro:Bold:13.0" \
    script="plugins/front_app.sh" \
  --subscribe front_app front_app_switched

sketchybar \
  --add item clock right \
  --set clock \
    update_freq=1 \
    script="plugins/clock.sh"

sketchybar \
  --add item wifi right\
  --set wifi icon=􀙇 \
  --set wifi icon.font="SF Pro:Regular:14"\
  --set wifi script="plugins/wifi.sh"\
  --subscribe wifi wifi_change mouse.clicked

sketchybar \
  --add item battery right\
  --set battery \
    icon.font="SF Pro:Regular:11" \
    label.font="SF Pro Text:Thin:16" \
    icon.padding_right=5 \
    script="plugins/battery.sh"\
    update_freq=120 \
  --subscribe battery \
    system_woke \
    power_source_change

sketchybar \
  --add item volume right\
  --set volume\
    script="plugins/volume.sh"\
    icon.font="SF Pro:Regular:11"\
    icon.padding_right=5\
    label.font="SF Pro Text:Thin:16"\
  --subscribe volume volume_change

sketchybar\
  --add item memory right\
  --set memory\
    label="􀫦"\
    label.font="SF Pro Text:Regular:16"\
    script="plugins/memory.sh"\
    update_freq=1\
    icon.padding_right=5\
    icon.font="SF Pro Text:Regular:11"\
  --subscribe memory mouse.clicked
    
sketchybar --hotload on --update
