#!/usr/bin/env bash

set -x

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_destroyed \
    action="if ! yabai -m query --windows --space | grep -q '.' ; then yabai -m query --windows --space | grep 'app' | head -n1 | awk '{print \$2}' | xargs -I {} osascript -e 'tell application \"{}\" to quit' ; fi"

set +x
printf "yabai: configuration loaded...\\n"
